language: java
sudo: false
jdk:
  - openjdk8
branches:
  only:
  - master
script: mvn clean install -Dmaven.test.skip=true
before_deploy:
  - sed -i 's/CONFIG_USER_PLACEHOLDER/'$CONFIG_USER'/g' manifest.yml
  - sed -i 's/CONFIG_PASSWORD_PLACEHOLDER/'$CONFIG_PASSWORD'/g' manifest.yml
deploy:
  - provider: cloudfoundry
    api: https://api.run.pivotal.io
    username: $PCF_USERNAME
    password: $PCF_PASSWORD
    organization: $PCF_ORG
    space: $PCF_SPACE
  - provider: bintray
    file: bintray.json
    user: $BINTRAY_USERNAME
    key: $BINTRAY_API_KEY
notifications:
  email: false
  slack:
    on_success: always
    on_failure: always
    rooms:
      secure: "ndcU4fN2+q2shSaMK9HFW8Z/hNhWmYZm4RTVHLoW7UnjSea+xj0xlG8PIO1cNxhdH1GhyC3nLKorZqJ3WRjHvMe7dtYKqITSFnRTBALw+5NZ28CHllAOQeHSHhiNUUNXXNocPMYQI+Q983ORDuqNiPOc4NqYf6k0h5NiyttZULL3hUiCFQTR4SEAoRLpnolU0zcmvgnbBkQINIDd5Qsj5Rt3MYVeMpsitcwgYZ8CVhPxs7Z+f9FqJo7OmDW/Y4cW4+kAU8XMPW2y6pm83o0ODvyDoDj8alkPcud4bJa4XcBV4SxArcp8nMXsfP/GQ4i8hBL+BPEocPjpEDtPA0gQpp2Xp7CHZQai+tYFir5Ik7/R2HGGSEAlM7djkJyWONOPtAmSwUIqTC/SKH4jxp3stfAEB8If3j8qxPWBYiqKuGsGTPkqae1NpE6OsEVwR4TI0euE+ttlq3KBHu/DbiCvqOmoSkeCYM+WmW6sMW9YKEtdaCesZz3NHr25icnKP9WlYz7jcCkVA9CQqrwwOee4mc7jygQ+NcGXSLlylrRPQEVtYaIOeRACi4Plw73FsLvaoGH6MGVWtyRRdVF9sCxdhPGgHE8a6ptToQRTBjvf7CSWGVJSxZhjRL+ftTGO4bWxjpdGFT0htJ17+uIUyKV9VyEqjH7olJ5KJldH3vcur+Q="
#    recipients:
#      - rajasushanth@outlook.com
