language: java
sudo: false
jdk:
  - openjdk8
branches:
  only:
  - master
script: mvn clean install -Dmaven.test.skip=true
deploy:
   provider: cloudfoundry
   api: https://api.run.pivotal.io
   username: $PCF_USERNAME
   password: $PCF_PASSWORD
   organization: $PCF_ORG
   space: $PCF_SPACE
#notifications:
#  email:
#    recipients:
#      - rajasushanth@outlook.com
#    on_success: always
#    on_failure: always
